---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "cicd"
  labels:
    name: "cicd"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins
  namespace: cicd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default-cinder
  resources:
    requests:
      storage: 3Gi

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
  namespace: cicd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: jenkins
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: jenkins
        image: hub.easystack.io/captain/jenkins-kubernetes:2.64
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 50000
            protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/jenkins
          name: home
      volumes:
        - name: home
          persistentVolumeClaim:
            claimName: jenkins

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  namespace: cicd
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 32502
    name: web
  - port: 50000
    targetPort: 50000
    name: slave
  selector:
    k8s-app: jenkins
